CREATE TABLE IF NOT EXISTS biz_project_archive (
  id BIGINT NOT NULL PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  project_id BIGINT NOT NULL,
  project_code VARCHAR(64) NOT NULL,
  project_name VARCHAR(255) NOT NULL,
  archive_date DATETIME NOT NULL,
  archived_by BIGINT NULL,
  archived_by_name VARCHAR(128) NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  task_count INT NOT NULL DEFAULT 0,
  work_order_count INT NOT NULL DEFAULT 0,
  rectification_count INT NOT NULL DEFAULT 0,
  document_count INT NOT NULL DEFAULT 0,
  snapshot_version VARCHAR(32) NOT NULL DEFAULT 'v1',
  snapshot_json LONGTEXT NOT NULL,
  created_at DATETIME NULL,
  created_by BIGINT NULL,
  updated_at DATETIME NULL,
  updated_by BIGINT NULL,
  deleted TINYINT NOT NULL DEFAULT 0,
  version BIGINT NOT NULL DEFAULT 0,
  remark VARCHAR(500) NULL,
  UNIQUE KEY uk_biz_project_archive_project (tenant_id, project_id),
  KEY idx_biz_project_archive_tenant_date (tenant_id, archive_date)
);
