CREATE TABLE IF NOT EXISTS biz_ai_model_config (
  id BIGINT NOT NULL PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  display_name VARCHAR(128) NOT NULL,
  provider_type VARCHAR(64) NOT NULL,
  provider_name VARCHAR(128) NOT NULL,
  base_url VARCHAR(500) NOT NULL,
  model_name VARCHAR(128) NOT NULL,
  api_key_cipher TEXT NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'online',
  default_model TINYINT NOT NULL DEFAULT 0,
  timeout_seconds INT NOT NULL DEFAULT 30,
  temperature DECIMAL(6,3) NULL,
  max_tokens INT NULL,
  remark VARCHAR(500) NULL,
  deleted TINYINT NOT NULL DEFAULT 0,
  version BIGINT NOT NULL DEFAULT 0,
  created_by BIGINT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_biz_ai_model_config_tenant (tenant_id, status),
  KEY idx_biz_ai_model_config_default (tenant_id, default_model)
);
