CREATE TABLE IF NOT EXISTS biz_ai_chat_trace (
  id BIGINT NOT NULL PRIMARY KEY,
  trace_id VARCHAR(64) NOT NULL,
  session_id VARCHAR(64) NULL,
  tenant_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  username VARCHAR(128) NULL,
  route_path VARCHAR(500) NULL,
  entity_type VARCHAR(64) NULL,
  entity_id VARCHAR(128) NULL,
  question TEXT NULL,
  answer MEDIUMTEXT NULL,
  status VARCHAR(64) NOT NULL,
  model_config_id BIGINT NULL,
  provider_type VARCHAR(64) NULL,
  model_name VARCHAR(128) NULL,
  tool_names_json TEXT NULL,
  citations_json MEDIUMTEXT NULL,
  latency_ms BIGINT NULL,
  error_message VARCHAR(1000) NULL,
  remark VARCHAR(500) NULL,
  deleted TINYINT NOT NULL DEFAULT 0,
  version BIGINT NOT NULL DEFAULT 0,
  created_by BIGINT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_biz_ai_chat_trace_id (trace_id),
  KEY idx_biz_ai_chat_trace_user_time (tenant_id, user_id, created_at),
  KEY idx_biz_ai_chat_trace_session (tenant_id, session_id),
  KEY idx_biz_ai_chat_trace_status (tenant_id, status)
);

CREATE TABLE IF NOT EXISTS biz_ai_chat_trace_event (
  id BIGINT NOT NULL PRIMARY KEY,
  trace_id VARCHAR(64) NOT NULL,
  tenant_id BIGINT NOT NULL,
  sequence_no INT NOT NULL,
  event_type VARCHAR(64) NOT NULL,
  event_name VARCHAR(128) NOT NULL,
  status VARCHAR(64) NOT NULL,
  detail_json MEDIUMTEXT NULL,
  elapsed_ms BIGINT NULL,
  remark VARCHAR(500) NULL,
  deleted TINYINT NOT NULL DEFAULT 0,
  version BIGINT NOT NULL DEFAULT 0,
  created_by BIGINT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_biz_ai_chat_trace_event_trace (tenant_id, trace_id, sequence_no),
  KEY idx_biz_ai_chat_trace_event_type (tenant_id, event_type, event_name)
);
