CREATE TABLE IF NOT EXISTS biz_control_plan (
  id BIGINT NOT NULL PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  plan_code VARCHAR(64) NOT NULL,
  plan_name VARCHAR(255) NOT NULL,
  cycle VARCHAR(32) NOT NULL,
  plan_year INT NOT NULL,
  period VARCHAR(64) NOT NULL,
  status VARCHAR(32) NOT NULL,
  description TEXT NULL,
  owner_scope_id BIGINT NOT NULL,
  shared_scope_ids VARCHAR(500) NULL,
  parent_id BIGINT NULL,
  approved_by BIGINT NULL,
  remark VARCHAR(500) NULL,
  deleted TINYINT NOT NULL DEFAULT 0,
  version BIGINT NOT NULL DEFAULT 0,
  created_by BIGINT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_biz_control_plan_code (tenant_id, plan_code),
  KEY idx_biz_control_plan_status (tenant_id, status),
  KEY idx_biz_control_plan_year (tenant_id, plan_year),
  KEY idx_biz_control_plan_parent (tenant_id, parent_id),
  KEY idx_biz_control_plan_scope (tenant_id, owner_scope_id)
);

CREATE TABLE IF NOT EXISTS biz_control_plan_item (
  id BIGINT NOT NULL PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  plan_id BIGINT NOT NULL,
  sequence_no INT NOT NULL DEFAULT 1,
  target_scope VARCHAR(255) NOT NULL,
  checklist_ids VARCHAR(500) NULL,
  planned_start_date DATE NOT NULL,
  planned_end_date DATE NOT NULL,
  assignee VARCHAR(64) NULL,
  project_id VARCHAR(64) NULL,
  remark VARCHAR(500) NULL,
  deleted TINYINT NOT NULL DEFAULT 0,
  version BIGINT NOT NULL DEFAULT 0,
  created_by BIGINT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_biz_control_plan_item_parent (tenant_id, plan_id),
  KEY idx_biz_control_plan_item_date (tenant_id, planned_start_date, planned_end_date)
);
