CREATE TABLE IF NOT EXISTS biz_project (
  id BIGINT NOT NULL PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  project_code VARCHAR(64) NOT NULL,
  project_name VARCHAR(255) NOT NULL,
  source VARCHAR(32) NOT NULL,
  plan_id BIGINT NULL,
  plan_name VARCHAR(255) NULL,
  description TEXT NULL,
  start_date DATE NOT NULL,
  end_date DATE NULL,
  status VARCHAR(32) NOT NULL,
  tag_ids VARCHAR(500) NULL,
  tag_names VARCHAR(1000) NULL,
  leader_id BIGINT NULL,
  leader_name VARCHAR(100) NULL,
  checklist_ids VARCHAR(1000) NULL,
  archive_status VARCHAR(32) NOT NULL DEFAULT 'none',
  archive_started_at DATETIME NULL,
  archive_completed_at DATETIME NULL,
  archive_error TEXT NULL,
  remark VARCHAR(500) NULL,
  deleted TINYINT NOT NULL DEFAULT 0,
  version BIGINT NOT NULL DEFAULT 0,
  created_by BIGINT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_biz_project_code (tenant_id, project_code),
  KEY idx_biz_project_status (tenant_id, status),
  KEY idx_biz_project_leader (tenant_id, leader_id)
);

CREATE TABLE IF NOT EXISTS biz_project_member (
  id BIGINT NOT NULL PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  project_id BIGINT NOT NULL,
  personnel_id BIGINT NOT NULL,
  personnel_name VARCHAR(100) NOT NULL,
  employee_no VARCHAR(64) NULL,
  department VARCHAR(100) NULL,
  role VARCHAR(32) NOT NULL,
  remark VARCHAR(500) NULL,
  deleted TINYINT NOT NULL DEFAULT 0,
  version BIGINT NOT NULL DEFAULT 0,
  created_by BIGINT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_biz_project_member_person (tenant_id, project_id, personnel_id, role),
  KEY idx_biz_project_member_project (tenant_id, project_id),
  KEY idx_biz_project_member_person (tenant_id, personnel_id)
);

CREATE TABLE IF NOT EXISTS biz_project_task (
  id BIGINT NOT NULL PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  project_id BIGINT NOT NULL,
  checklist_id BIGINT NOT NULL,
  checklist_name VARCHAR(255) NULL,
  checklist_item_id BIGINT NOT NULL,
  check_content TEXT NOT NULL,
  check_criterion TEXT NOT NULL,
  control_frequency VARCHAR(64) NULL,
  evaluation_type VARCHAR(64) NULL,
  task_name VARCHAR(255) NULL,
  task_description TEXT NULL,
  assignee_id BIGINT NULL,
  assignee_name VARCHAR(100) NULL,
  contact_id BIGINT NULL,
  contact_name VARCHAR(100) NULL,
  status VARCHAR(32) NOT NULL,
  issued_at DATETIME NULL,
  completed_at DATETIME NULL,
  remark VARCHAR(500) NULL,
  deleted TINYINT NOT NULL DEFAULT 0,
  version BIGINT NOT NULL DEFAULT 0,
  created_by BIGINT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_biz_project_task_item (tenant_id, project_id, checklist_item_id),
  KEY idx_biz_project_task_project (tenant_id, project_id),
  KEY idx_biz_project_task_assignee (tenant_id, assignee_id),
  KEY idx_biz_project_task_status (tenant_id, status)
);

CREATE TABLE IF NOT EXISTS biz_project_task_work_order (
  id BIGINT NOT NULL PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  project_id BIGINT NOT NULL,
  task_id BIGINT NOT NULL,
  oms_work_order_id VARCHAR(100) NULL,
  idempotency_key VARCHAR(160) NOT NULL,
  handler_id BIGINT NOT NULL,
  handler_name VARCHAR(100) NOT NULL,
  work_order_title VARCHAR(255) NULL,
  work_order_description TEXT NULL,
  issued_at DATETIME NULL,
  completed_at DATETIME NULL,
  oms_status VARCHAR(32) NULL,
  oms_status_name VARCHAR(100) NULL,
  oms_result_summary TEXT NULL,
  oms_detail_payload TEXT NULL,
  oms_log_payload TEXT NULL,
  oms_attachment_payload TEXT NULL,
  sync_status VARCHAR(32) NOT NULL DEFAULT 'not_synced',
  last_synced_at DATETIME NULL,
  sync_error TEXT NULL,
  request_payload TEXT NULL,
  response_payload TEXT NULL,
  iris_review_status VARCHAR(32) NOT NULL DEFAULT 'pending',
  iris_review_opinion TEXT NULL,
  iris_reviewed_at DATETIME NULL,
  iris_reviewed_by BIGINT NULL,
  rectification_id BIGINT NULL,
  review_locked TINYINT NOT NULL DEFAULT 0,
  archive_batch_id VARCHAR(64) NULL,
  detail_snapshot_json TEXT NULL,
  log_snapshot_json TEXT NULL,
  attachment_snapshot_json TEXT NULL,
  snapshot_version VARCHAR(32) NULL,
  snapshotted_at DATETIME NULL,
  remark VARCHAR(500) NULL,
  deleted TINYINT NOT NULL DEFAULT 0,
  version BIGINT NOT NULL DEFAULT 0,
  created_by BIGINT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_biz_project_wo_idempotency (tenant_id, idempotency_key),
  UNIQUE KEY uk_biz_project_wo_handler (tenant_id, task_id, handler_id),
  KEY idx_biz_project_wo_task (tenant_id, task_id),
  KEY idx_biz_project_wo_project (tenant_id, project_id),
  KEY idx_biz_project_wo_oms (tenant_id, oms_work_order_id),
  KEY idx_biz_project_wo_review (tenant_id, iris_review_status)
);

CREATE TABLE IF NOT EXISTS biz_project_rectification (
  id BIGINT NOT NULL PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  rectification_code VARCHAR(64) NOT NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT NULL,
  task_name VARCHAR(255) NULL,
  task_description TEXT NULL,
  project_id BIGINT NOT NULL,
  project_name VARCHAR(255) NOT NULL,
  task_id BIGINT NOT NULL,
  checklist_item_id BIGINT NOT NULL,
  check_content TEXT NULL,
  source_work_order_record_id BIGINT NOT NULL,
  oms_work_order_id VARCHAR(100) NULL,
  assignee_id BIGINT NULL,
  assignee_name VARCHAR(100) NULL,
  contact_id BIGINT NULL,
  contact_name VARCHAR(100) NULL,
  issued_at DATETIME NULL,
  deadline DATETIME NULL,
  status VARCHAR(32) NOT NULL,
  remark VARCHAR(500) NULL,
  deleted TINYINT NOT NULL DEFAULT 0,
  version BIGINT NOT NULL DEFAULT 0,
  created_by BIGINT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_biz_project_rect_code (tenant_id, rectification_code),
  UNIQUE KEY uk_biz_project_rect_source (tenant_id, source_work_order_record_id),
  KEY idx_biz_project_rect_project (tenant_id, project_id),
  KEY idx_biz_project_rect_status (tenant_id, status)
);

CREATE TABLE IF NOT EXISTS biz_project_operation_log (
  id BIGINT NOT NULL PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  project_id BIGINT NOT NULL,
  task_id BIGINT NULL,
  work_order_id BIGINT NULL,
  action VARCHAR(64) NOT NULL,
  operator_id BIGINT NULL,
  operator_name VARCHAR(100) NULL,
  remark TEXT NULL,
  deleted TINYINT NOT NULL DEFAULT 0,
  version BIGINT NOT NULL DEFAULT 0,
  created_by BIGINT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_biz_project_log_project (tenant_id, project_id),
  KEY idx_biz_project_log_task (tenant_id, task_id),
  KEY idx_biz_project_log_work_order (tenant_id, work_order_id)
);
