CREATE DATABASE IF NOT EXISTS iris_back
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_unicode_ci;

USE iris_back;

CREATE TABLE IF NOT EXISTS sys_tenant (
  id BIGINT NOT NULL PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  tenant_code VARCHAR(64) NOT NULL,
  tenant_name VARCHAR(128) NOT NULL,
  status TINYINT NOT NULL DEFAULT 1,
  remark VARCHAR(500) NULL,
  deleted TINYINT NOT NULL DEFAULT 0,
  version BIGINT NOT NULL DEFAULT 0,
  created_by BIGINT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_sys_tenant_code (tenant_code),
  KEY idx_sys_tenant_status (status)
);

CREATE TABLE IF NOT EXISTS sys_org (
  id BIGINT NOT NULL PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  parent_id BIGINT NULL,
  org_code VARCHAR(64) NOT NULL,
  org_name VARCHAR(128) NOT NULL,
  org_level INT NOT NULL DEFAULT 1,
  sort_order INT NOT NULL DEFAULT 0,
  status TINYINT NOT NULL DEFAULT 1,
  remark VARCHAR(500) NULL,
  deleted TINYINT NOT NULL DEFAULT 0,
  version BIGINT NOT NULL DEFAULT 0,
  created_by BIGINT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_sys_org_code (tenant_id, org_code),
  KEY idx_sys_org_parent (tenant_id, parent_id)
);

CREATE TABLE IF NOT EXISTS sys_user (
  id BIGINT NOT NULL PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  org_id BIGINT NULL,
  account VARCHAR(64) NOT NULL,
  username VARCHAR(128) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  email VARCHAR(128) NULL,
  mobile VARCHAR(32) NULL,
  status TINYINT NOT NULL DEFAULT 1,
  remark VARCHAR(500) NULL,
  deleted TINYINT NOT NULL DEFAULT 0,
  version BIGINT NOT NULL DEFAULT 0,
  created_by BIGINT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_sys_user_account (tenant_id, account),
  KEY idx_sys_user_org (tenant_id, org_id)
);

CREATE TABLE IF NOT EXISTS sys_role (
  id BIGINT NOT NULL PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  role_code VARCHAR(64) NOT NULL,
  role_name VARCHAR(128) NOT NULL,
  scope_type VARCHAR(32) NOT NULL DEFAULT 'BUSINESS',
  status TINYINT NOT NULL DEFAULT 1,
  remark VARCHAR(500) NULL,
  deleted TINYINT NOT NULL DEFAULT 0,
  version BIGINT NOT NULL DEFAULT 0,
  created_by BIGINT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_sys_role_code (tenant_id, role_code)
);

CREATE TABLE IF NOT EXISTS sys_user_role (
  id BIGINT NOT NULL PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  role_id BIGINT NOT NULL,
  remark VARCHAR(500) NULL,
  deleted TINYINT NOT NULL DEFAULT 0,
  version BIGINT NOT NULL DEFAULT 0,
  created_by BIGINT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_sys_user_role (tenant_id, user_id, role_id)
);

CREATE TABLE IF NOT EXISTS sys_permission (
  id BIGINT NOT NULL PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  permission_code VARCHAR(64) NOT NULL,
  permission_name VARCHAR(128) NOT NULL,
  permission_type VARCHAR(32) NOT NULL DEFAULT 'API',
  path VARCHAR(255) NULL,
  method VARCHAR(16) NULL,
  status TINYINT NOT NULL DEFAULT 1,
  remark VARCHAR(500) NULL,
  deleted TINYINT NOT NULL DEFAULT 0,
  version BIGINT NOT NULL DEFAULT 0,
  created_by BIGINT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_sys_permission_code (tenant_id, permission_code)
);

CREATE TABLE IF NOT EXISTS sys_role_permission (
  id BIGINT NOT NULL PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  role_id BIGINT NOT NULL,
  permission_id BIGINT NOT NULL,
  remark VARCHAR(500) NULL,
  deleted TINYINT NOT NULL DEFAULT 0,
  version BIGINT NOT NULL DEFAULT 0,
  created_by BIGINT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_sys_role_permission (tenant_id, role_id, permission_id)
);

CREATE TABLE IF NOT EXISTS sys_role_menu (
  id BIGINT NOT NULL PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  role_id BIGINT NOT NULL,
  menu_code VARCHAR(128) NOT NULL,
  remark VARCHAR(500) NULL,
  deleted TINYINT NOT NULL DEFAULT 0,
  version BIGINT NOT NULL DEFAULT 0,
  created_by BIGINT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_sys_role_menu (tenant_id, role_id, menu_code),
  KEY idx_sys_role_menu_role (tenant_id, role_id)
);

CREATE TABLE IF NOT EXISTS sys_resource_scope (
  id BIGINT NOT NULL PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  scope_code VARCHAR(64) NOT NULL,
  scope_name VARCHAR(128) NOT NULL,
  status TINYINT NOT NULL DEFAULT 1,
  remark VARCHAR(500) NULL,
  deleted TINYINT NOT NULL DEFAULT 0,
  version BIGINT NOT NULL DEFAULT 0,
  created_by BIGINT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_sys_resource_scope_code (tenant_id, scope_code)
);

CREATE TABLE IF NOT EXISTS sys_resource_scope_member (
  id BIGINT NOT NULL PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  scope_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  can_view TINYINT NOT NULL DEFAULT 1,
  can_create TINYINT NOT NULL DEFAULT 0,
  can_edit TINYINT NOT NULL DEFAULT 0,
  can_delete TINYINT NOT NULL DEFAULT 0,
  can_manage TINYINT NOT NULL DEFAULT 0,
  remark VARCHAR(500) NULL,
  deleted TINYINT NOT NULL DEFAULT 0,
  version BIGINT NOT NULL DEFAULT 0,
  created_by BIGINT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_sys_resource_scope_member (tenant_id, scope_id, user_id),
  KEY idx_sys_resource_scope_member_user (tenant_id, user_id)
);

CREATE TABLE IF NOT EXISTS biz_standard (
  id BIGINT NOT NULL PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  standard_group_id VARCHAR(64) NOT NULL,
  standard_code VARCHAR(64) NOT NULL,
  title VARCHAR(255) NOT NULL,
  category VARCHAR(32) NOT NULL,
  standard_version VARCHAR(64) NOT NULL,
  version_number INT NOT NULL DEFAULT 1,
  previous_version_id BIGINT NULL,
  publish_date DATE NULL,
  status VARCHAR(32) NOT NULL,
  description TEXT NULL,
  visibility_level VARCHAR(32) NOT NULL DEFAULT 'PUBLIC',
  owner_scope_id BIGINT NOT NULL,
  shared_scope_ids VARCHAR(500) NULL,
  change_log VARCHAR(500) NULL,
  remark VARCHAR(500) NULL,
  deleted TINYINT NOT NULL DEFAULT 0,
  version BIGINT NOT NULL DEFAULT 0,
  created_by BIGINT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_biz_standard_group (tenant_id, standard_group_id),
  KEY idx_biz_standard_scope (tenant_id, owner_scope_id),
  KEY idx_biz_standard_status (tenant_id, status)
);

CREATE TABLE IF NOT EXISTS biz_control_checklist (
  id BIGINT NOT NULL PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  checklist_code VARCHAR(64) NOT NULL,
  checklist_name VARCHAR(255) NOT NULL,
  description TEXT NULL,
  checklist_version VARCHAR(64) NOT NULL,
  owner_scope_id BIGINT NOT NULL,
  shared_scope_ids VARCHAR(500) NULL,
  upload_date DATE NULL,
  status VARCHAR(32) NOT NULL,
  remark VARCHAR(500) NULL,
  deleted TINYINT NOT NULL DEFAULT 0,
  version BIGINT NOT NULL DEFAULT 0,
  created_by BIGINT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_biz_control_checklist_code (tenant_id, checklist_code),
  KEY idx_biz_control_checklist_status (tenant_id, status),
  KEY idx_biz_control_checklist_scope (tenant_id, owner_scope_id)
);

CREATE TABLE IF NOT EXISTS biz_control_checklist_item (
  id BIGINT NOT NULL PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  checklist_id BIGINT NOT NULL,
  sequence_no INT NOT NULL DEFAULT 1,
  content TEXT NOT NULL,
  criterion TEXT NOT NULL,
  control_frequency VARCHAR(64) NOT NULL,
  evaluation_type VARCHAR(64) NOT NULL,
  organization_ids VARCHAR(500) NULL,
  remark VARCHAR(500) NULL,
  deleted TINYINT NOT NULL DEFAULT 0,
  version BIGINT NOT NULL DEFAULT 0,
  created_by BIGINT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_biz_control_checklist_item_parent (tenant_id, checklist_id),
  KEY idx_biz_control_checklist_item_frequency (tenant_id, control_frequency)
);

CREATE TABLE IF NOT EXISTS biz_control_plan (
  id BIGINT NOT NULL PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  plan_code VARCHAR(64) NOT NULL,
  plan_name VARCHAR(255) NOT NULL,
  cycle VARCHAR(32) NOT NULL,
  plan_year INT NOT NULL,
  period VARCHAR(64) NOT NULL,
  status VARCHAR(32) NOT NULL,
  description TEXT NULL,
  owner_scope_id BIGINT NOT NULL,
  shared_scope_ids VARCHAR(500) NULL,
  parent_id BIGINT NULL,
  approved_by BIGINT NULL,
  remark VARCHAR(500) NULL,
  deleted TINYINT NOT NULL DEFAULT 0,
  version BIGINT NOT NULL DEFAULT 0,
  created_by BIGINT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_biz_control_plan_code (tenant_id, plan_code),
  KEY idx_biz_control_plan_status (tenant_id, status),
  KEY idx_biz_control_plan_year (tenant_id, plan_year),
  KEY idx_biz_control_plan_parent (tenant_id, parent_id),
  KEY idx_biz_control_plan_scope (tenant_id, owner_scope_id)
);

CREATE TABLE IF NOT EXISTS biz_control_plan_item (
  id BIGINT NOT NULL PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  plan_id BIGINT NOT NULL,
  sequence_no INT NOT NULL DEFAULT 1,
  target_scope VARCHAR(255) NOT NULL,
  checklist_ids VARCHAR(500) NULL,
  planned_start_date DATE NOT NULL,
  planned_end_date DATE NOT NULL,
  assignee VARCHAR(64) NULL,
  project_id VARCHAR(64) NULL,
  remark VARCHAR(500) NULL,
  deleted TINYINT NOT NULL DEFAULT 0,
  version BIGINT NOT NULL DEFAULT 0,
  created_by BIGINT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_biz_control_plan_item_parent (tenant_id, plan_id),
  KEY idx_biz_control_plan_item_date (tenant_id, planned_start_date, planned_end_date)
);

CREATE TABLE IF NOT EXISTS biz_project (
  id BIGINT NOT NULL PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  project_code VARCHAR(64) NOT NULL,
  project_name VARCHAR(255) NOT NULL,
  source VARCHAR(32) NOT NULL,
  plan_id BIGINT NULL,
  plan_name VARCHAR(255) NULL,
  description TEXT NULL,
  start_date DATE NOT NULL,
  end_date DATE NULL,
  status VARCHAR(32) NOT NULL,
  tag_ids VARCHAR(500) NULL,
  tag_names VARCHAR(1000) NULL,
  leader_id BIGINT NULL,
  leader_name VARCHAR(100) NULL,
  checklist_ids VARCHAR(1000) NULL,
  archive_status VARCHAR(32) NOT NULL DEFAULT 'none',
  archive_started_at DATETIME NULL,
  archive_completed_at DATETIME NULL,
  archive_error TEXT NULL,
  remark VARCHAR(500) NULL,
  deleted TINYINT NOT NULL DEFAULT 0,
  version BIGINT NOT NULL DEFAULT 0,
  created_by BIGINT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_biz_project_code (tenant_id, project_code),
  KEY idx_biz_project_status (tenant_id, status),
  KEY idx_biz_project_leader (tenant_id, leader_id)
);

CREATE TABLE IF NOT EXISTS biz_project_member (
  id BIGINT NOT NULL PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  project_id BIGINT NOT NULL,
  personnel_id BIGINT NOT NULL,
  personnel_name VARCHAR(100) NOT NULL,
  employee_no VARCHAR(64) NULL,
  department VARCHAR(100) NULL,
  role VARCHAR(32) NOT NULL,
  remark VARCHAR(500) NULL,
  deleted TINYINT NOT NULL DEFAULT 0,
  version BIGINT NOT NULL DEFAULT 0,
  created_by BIGINT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_biz_project_member_person (tenant_id, project_id, personnel_id, role),
  KEY idx_biz_project_member_project (tenant_id, project_id),
  KEY idx_biz_project_member_person (tenant_id, personnel_id)
);

CREATE TABLE IF NOT EXISTS biz_project_task (
  id BIGINT NOT NULL PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  project_id BIGINT NOT NULL,
  checklist_id BIGINT NOT NULL,
  checklist_name VARCHAR(255) NULL,
  checklist_item_id BIGINT NOT NULL,
  check_content TEXT NOT NULL,
  check_criterion TEXT NOT NULL,
  control_frequency VARCHAR(64) NULL,
  evaluation_type VARCHAR(64) NULL,
  task_name VARCHAR(255) NULL,
  task_description TEXT NULL,
  assignee_id BIGINT NULL,
  assignee_name VARCHAR(100) NULL,
  contact_id BIGINT NULL,
  contact_name VARCHAR(100) NULL,
  status VARCHAR(32) NOT NULL,
  issued_at DATETIME NULL,
  completed_at DATETIME NULL,
  remark VARCHAR(500) NULL,
  deleted TINYINT NOT NULL DEFAULT 0,
  version BIGINT NOT NULL DEFAULT 0,
  created_by BIGINT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_biz_project_task_item (tenant_id, project_id, checklist_item_id),
  KEY idx_biz_project_task_project (tenant_id, project_id),
  KEY idx_biz_project_task_assignee (tenant_id, assignee_id),
  KEY idx_biz_project_task_status (tenant_id, status)
);

CREATE TABLE IF NOT EXISTS biz_project_task_work_order (
  id BIGINT NOT NULL PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  project_id BIGINT NOT NULL,
  task_id BIGINT NOT NULL,
  oms_work_order_id VARCHAR(100) NULL,
  idempotency_key VARCHAR(160) NOT NULL,
  handler_id BIGINT NOT NULL,
  handler_name VARCHAR(100) NOT NULL,
  work_order_title VARCHAR(255) NULL,
  work_order_description TEXT NULL,
  issued_at DATETIME NULL,
  completed_at DATETIME NULL,
  oms_status VARCHAR(32) NULL,
  oms_status_name VARCHAR(100) NULL,
  oms_result_summary TEXT NULL,
  oms_detail_payload TEXT NULL,
  oms_log_payload TEXT NULL,
  oms_attachment_payload TEXT NULL,
  sync_status VARCHAR(32) NOT NULL DEFAULT 'not_synced',
  last_synced_at DATETIME NULL,
  sync_error TEXT NULL,
  request_payload TEXT NULL,
  response_payload TEXT NULL,
  iris_review_status VARCHAR(32) NOT NULL DEFAULT 'pending',
  iris_review_opinion TEXT NULL,
  iris_reviewed_at DATETIME NULL,
  iris_reviewed_by BIGINT NULL,
  rectification_id BIGINT NULL,
  review_locked TINYINT NOT NULL DEFAULT 0,
  archive_batch_id VARCHAR(64) NULL,
  detail_snapshot_json TEXT NULL,
  log_snapshot_json TEXT NULL,
  attachment_snapshot_json TEXT NULL,
  snapshot_version VARCHAR(32) NULL,
  snapshotted_at DATETIME NULL,
  remark VARCHAR(500) NULL,
  deleted TINYINT NOT NULL DEFAULT 0,
  version BIGINT NOT NULL DEFAULT 0,
  created_by BIGINT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_biz_project_wo_idempotency (tenant_id, idempotency_key),
  UNIQUE KEY uk_biz_project_wo_handler (tenant_id, task_id, handler_id),
  KEY idx_biz_project_wo_task (tenant_id, task_id),
  KEY idx_biz_project_wo_project (tenant_id, project_id),
  KEY idx_biz_project_wo_oms (tenant_id, oms_work_order_id),
  KEY idx_biz_project_wo_review (tenant_id, iris_review_status)
);

CREATE TABLE IF NOT EXISTS biz_project_rectification (
  id BIGINT NOT NULL PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  rectification_code VARCHAR(64) NOT NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT NULL,
  task_name VARCHAR(255) NULL,
  task_description TEXT NULL,
  project_id BIGINT NOT NULL,
  project_name VARCHAR(255) NOT NULL,
  task_id BIGINT NOT NULL,
  checklist_item_id BIGINT NOT NULL,
  check_content TEXT NULL,
  source_work_order_record_id BIGINT NOT NULL,
  oms_work_order_id VARCHAR(100) NULL,
  assignee_id BIGINT NULL,
  assignee_name VARCHAR(100) NULL,
  contact_id BIGINT NULL,
  contact_name VARCHAR(100) NULL,
  issued_at DATETIME NULL,
  deadline DATETIME NULL,
  status VARCHAR(32) NOT NULL,
  remark VARCHAR(500) NULL,
  deleted TINYINT NOT NULL DEFAULT 0,
  version BIGINT NOT NULL DEFAULT 0,
  created_by BIGINT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_biz_project_rect_code (tenant_id, rectification_code),
  UNIQUE KEY uk_biz_project_rect_source (tenant_id, source_work_order_record_id),
  KEY idx_biz_project_rect_project (tenant_id, project_id),
  KEY idx_biz_project_rect_status (tenant_id, status)
);

CREATE TABLE IF NOT EXISTS biz_project_operation_log (
  id BIGINT NOT NULL PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  project_id BIGINT NOT NULL,
  task_id BIGINT NULL,
  work_order_id BIGINT NULL,
  action VARCHAR(64) NOT NULL,
  operator_id BIGINT NULL,
  operator_name VARCHAR(100) NULL,
  remark TEXT NULL,
  deleted TINYINT NOT NULL DEFAULT 0,
  version BIGINT NOT NULL DEFAULT 0,
  created_by BIGINT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_biz_project_log_project (tenant_id, project_id),
  KEY idx_biz_project_log_task (tenant_id, task_id),
  KEY idx_biz_project_log_work_order (tenant_id, work_order_id)
);

CREATE TABLE IF NOT EXISTS sys_file (
  id BIGINT NOT NULL PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  bucket_name VARCHAR(128) NOT NULL,
  object_key VARCHAR(500) NOT NULL,
  file_name VARCHAR(255) NOT NULL,
  file_ext VARCHAR(32) NULL,
  content_type VARCHAR(128) NULL,
  file_size BIGINT NOT NULL DEFAULT 0,
  storage_type VARCHAR(32) NOT NULL DEFAULT 'MINIO',
  etag VARCHAR(128) NULL,
  remark VARCHAR(500) NULL,
  deleted TINYINT NOT NULL DEFAULT 0,
  version BIGINT NOT NULL DEFAULT 0,
  created_by BIGINT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_sys_file_tenant (tenant_id, id),
  KEY idx_sys_file_object (tenant_id, bucket_name, object_key(100))
);

CREATE TABLE IF NOT EXISTS sys_file_ref (
  id BIGINT NOT NULL PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  file_id BIGINT NOT NULL,
  biz_type VARCHAR(64) NOT NULL,
  biz_id BIGINT NOT NULL,
  category VARCHAR(64) NULL,
  sort_no INT NOT NULL DEFAULT 0,
  remark VARCHAR(500) NULL,
  deleted TINYINT NOT NULL DEFAULT 0,
  version BIGINT NOT NULL DEFAULT 0,
  created_by BIGINT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_sys_file_ref (tenant_id, file_id, biz_type, biz_id),
  KEY idx_sys_file_ref_biz (tenant_id, biz_type, biz_id),
  KEY idx_sys_file_ref_file (tenant_id, file_id)
);

CREATE TABLE IF NOT EXISTS sys_login_log (
  id BIGINT NOT NULL PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  user_id BIGINT NULL,
  account VARCHAR(64) NULL,
  login_result VARCHAR(32) NOT NULL,
  ip_address VARCHAR(64) NULL,
  user_agent VARCHAR(500) NULL,
  login_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  remark VARCHAR(500) NULL,
  deleted TINYINT NOT NULL DEFAULT 0,
  version BIGINT NOT NULL DEFAULT 0,
  created_by BIGINT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_sys_login_log_user (tenant_id, user_id),
  KEY idx_sys_login_log_time (tenant_id, login_at)
);

CREATE TABLE IF NOT EXISTS sys_operation_log (
  id BIGINT NOT NULL PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  user_id BIGINT NULL,
  module_name VARCHAR(64) NOT NULL,
  operation_name VARCHAR(128) NOT NULL,
  request_uri VARCHAR(255) NULL,
  request_method VARCHAR(16) NULL,
  operation_result VARCHAR(32) NOT NULL DEFAULT 'SUCCESS',
  operation_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  remark VARCHAR(500) NULL,
  deleted TINYINT NOT NULL DEFAULT 0,
  version BIGINT NOT NULL DEFAULT 0,
  created_by BIGINT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_sys_operation_log_user (tenant_id, user_id),
  KEY idx_sys_operation_log_time (tenant_id, operation_at)
);
